# Generated by Django 5.0.4 on 2024-04-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team_images/')),
                ('bio', models.TextField()),
                ('twitter_url', models.URLField(blank=True)),
                ('behance_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
            ],
        ),
    ]
