# Generated by Django 5.0.4 on 2024-04-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('email', models.EmailField(max_length=255, verbose_name='E-Mail')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='Twitter URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
            ],
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
