# Generated by Django 5.0.4 on 2024-04-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bannercontactinfo_delete_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Services_Icon', models.CharField(choices=[('flaticon_money-1', 'flaticon_money-1'), ('flaticon_sedan-car-front', 'flaticon_sedan-car-front'), ('flaticon_shelter', 'flaticon_shelter'), ('flaticon_dollar', 'flaticon_dollar'), ('flaticon_trend', 'flaticon_trend'), ('flaticon_plumber', 'flaticon_plumber'), ('flaticon_building', 'flaticon_building'), ('flaticon_handcuff', 'flaticon_handcuff')], default='flaticon_handcuff', max_length=25)),
                ('headers', models.CharField(max_length=255, verbose_name='Headers')),
                ('Description', models.CharField(max_length=255, verbose_name='Description')),
                ('image', models.ImageField(upload_to='services_image/')),
            ],
        ),
    ]
