# Generated by Django 5.0.4 on 2024-04-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Services_Icon',
            field=models.CharField(choices=[('flaticon-money-1', 'flaticon-money-1'), ('flaticon-sedan-car-front', 'flaticon-sedan-car-front'), ('flaticon-shelter', 'flaticon-shelter'), ('flaticon-dollar', 'flaticon-dollar'), ('flaticon-trend', 'flaticon-trend'), ('flaticon-plumber', 'flaticon-plumber'), ('flaticon-building', 'flaticon-building'), ('flaticon-handcuff', 'flaticon-handcuff')], default='flaticon-handcuff', max_length=25),
        ),
    ]
