# Generated by Django 5.0.4 on 2024-04-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_services_services_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSocialMedya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SocialMedya', models.CharField(max_length=30)),
                ('SocialMedyaIcon', models.CharField(choices=[('icofont-twitter', 'icofont-twitter'), ('icofont-instagram', 'icofont-instagram'), ('icofont-facebook', 'icofont-facebook'), ('icofont-youtube', 'icofont-youtube'), ('icofont-linkedin', 'icofont-linkedin')], default='flaticon-handcuff', max_length=25)),
                ('social_url', models.URLField(blank=True, null=True, verbose_name='Social URL')),
            ],
        ),
    ]
