# Generated by Django 5.0.4 on 2024-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_footersocialmedya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersocialmedya',
            name='SocialMedyaIcon',
            field=models.CharField(choices=[('icofont-twitter', 'icofont-twitter'), ('icofont-instagram', 'icofont-instagram'), ('icofont-facebook', 'icofont-facebook'), ('icofont-youtube', 'icofont-youtube'), ('icofont-linkedin', 'icofont-linkedin')], max_length=25),
        ),
    ]
