# Generated by Django 5.0.4 on 2024-04-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
